### ISSUE TITLE
Projects Overview Redesign

### ISSUE THREAD

**Issue by stellarmagnet** [AutarkLabs/open-enterprise#1023]
Revise the Projects Overview tab to include lists of issue curations and funding proposals.

Design: https://projects.invisionapp.com/d/main#/console/17635937/366696855/preview

Spec: https://docs.google.com/document/d/1YErknw9EAjo3u-S7VdSXXMtPLfs7LLC8ly4Y7kVtEs0/edit#heading=h.qce16xujhg2c

[Note: we cannot show Pending curations or funding proposals until we have the Forwarder API integrated]

**Comment by jayalaves** [comment]
Left my comments on the InVision design file, but I'll summarize my three main points here:
- In the overview project cards, show issues and bounties instead of commits and contributors, since the latter are more connected to the GitHub environment than to the Aragon one, which is the one that users are experiencing at the moment.
- Pagination instead of 'Show more' buttons for the tables underneath, to avoid irregular white space when the user wants to view more items only on one of the two lists.
- The percentage item could be easier to notice if we increased the font weight, changed the color, or added a small progress bar next to it denoting the vote %, or a mix of these patterns.

**Comment by chadoh** [comment]
This is covered by #1113
