### ISSUE TITLE
Decisions.js (in dot voting) perpetually rerenders

### ISSUE THREAD

**Issue by Schwartz10** [AutarkLabs/open-enterprise#1075]
Not sure what's causing this, but i just noticed.

**Comment by Schwartz10** [comment]
Oh I see what it is: is there a better way to do this? 

https://github.com/AutarkLabs/planning-suite/blob/dev/apps/dot-voting/app/Decisions.js#L43

**Comment by Schwartz10** [comment]
I would recommend not passing this time as a prop, and instead calculating this at the lowest level if possible (everything is getting rerendered in this component since state is changing)

**Comment by stellarmagnet** [comment]
This may not be an issue once we implement #1114

**Comment by rkzel** [comment]
This particular functionality moved to <App> level, and changed from 'refresh every second' to 'refresh 5 seconds after the nearest vote finishes'. App level, because it's not enough to reload components further down the hierarchy, and 5 seconds because it might not be enough for results to come through - in my testing I observed sequence of reloads when that time was shorter. We'll see if it needs other adjustments after testing on rinkeby.
