### ISSUE TITLE
Show validation error in Address Book when adding a duplicate address

### ISSUE THREAD

**Issue by stellarmagnet** [AutarkLabs/open-enterprise#1173]
Right now you hit submit and it goes to the next panel that says action is impossible. it doesnt tell you why

**Comment by e18r** [comment]
I was going to open this very same issue and then I realized it was already created and assigned to me...

**Comment by ottodevs** [comment]
Shouldn't we create design elements for this? Other validation errors like "D - 1.3.1 New Allocation - Amount > Widget" have their figma design screens for validation errors/warnings cc @stellarmagnet doing this will prevent wrong implementations or differences between the task asked and the product since we could have a design reference and iterate over it in case we want to do design changes or aragon-ui updates these related components in the future

**Comment by chadoh** [comment]
It seems we have this problem again.
