### ISSUE TITLE
Improve date validation for New Reward

### ISSUE THREAD

**Issue by stellarmagnet** [AutarkLabs/open-enterprise#1489]
### One-time Merit
* Check with @topocount with whether they can be in the past

### One-time Dividend
* We should allow reference dates that are in the past or the same day.
* We should not allow the reference date to be a date prior to when the reference token was created: `The selected reference date occurs before the reference asset ANT was created. Please choose another date.`
   * ... Where `ANT` is the token symbol.

### Recurring Dividend
* We should allow start & end dates that are in the past or the same day.
* We should not allow either of these dates to be prior to when the reference token was created: `The selected reference date occurs before the reference asset ANT was created. Please choose another date.`

For all use cases, please test that when you do create a new reward for a date in the past (and it is a valid date in the past), that the new reward is:
* Properly created
* Properly claimed

**Comment by jayalaves** [comment]
@stellarmagnet @e18r 

As far as the UI design goes, there are no changes to be made on this end since there are no views that deal with input validation errors. (Unnecessary since we're familiar with the design pattern.)

I've updated the design specifications for the Rewards app, under [input validation](https://www.notion.so/autark/Design-specifications-fdb1c20d8adc48c6971a1760ef2c0248#1298932f36324453af620eab092ebebb), with a more generically simplified error message than what Yalda suggested, let me know what you think!

PS: Is there a way to specify in the error what the reference asset's creation date is? If the answer is yes and not's too complicated, I think it'd be a valuable feedback to reflect.

**Comment by e18r** [comment]
Hi @jayalaves, thank you for your review. Yesterday I submitted PR #1500 with @stellarmagnet's original validation message, but it can be changed to your current proposal or something else. Bear in mind that I already implemented the functionality to include variables in error messages, so it is possible now to include the reference asset's creation date.

However, since the PR is already submitted and someone might already be reviewing it, let me propose you something else: how about we leave that message change for a follow up PR? It would be a very simple change, and also you could include variables in other error messages in the New Rewards side panel, if you feel so inclined.

**Comment by jayalaves** [comment]
No problem, thanks for the update @e18r! Good to know that a fix is in progress, and I will update the docs once the PR is approved.
