### ISSUE TITLE
Implement accounting period summary section

### ISSUE THREAD

**Issue by stellarmagnet** [AutarkLabs/open-enterprise#1576]
Implement the accounting period summary section on the allocations app, to have a better view into what the accounting period is, and budget and spending metrics

WIP design:
https://www.figma.com/file/9c4GAhAa1LhH1TmJC8vCHA/Allocations?node-id=192%3A2032

Screenshot (may not be up-to-date with designs; check Figma link above)

<img width="718" alt="Screen Shot 2019-12-11 at 08 26 54" src="https://user-images.githubusercontent.com/221614/70625259-0f3d5480-1bf0-11ea-86a7-142f4b154f65.png">

**Comment by jayalaves** [comment]
Design available [here](https://www.figma.com/file/9c4GAhAa1LhH1TmJC8vCHA/Allocations?node-id=878%3A20278) has been merged with the Figma master branch, ready for production.

**Comment by javieralaves** [comment]
@PeterMPhillips Some minor tweaks needed here before I mark this one off:
- Change the font style of the metrics to `title2` (26px) and `body` 16px instead of `title4` and `body3`
- Adjust the metrics' upper and lower margin to 24px with respect to their container

[Reference for both changes here.](https://www.figma.com/file/9c4GAhAa1LhH1TmJC8vCHA/Allocations?node-id=1170%3A19929)

**Comment by javieralaves** [comment]
We can take care of the little styling details later on; I'm closing this for now as it works as expected.
