### ISSUE TITLE
Show estimated/actual time for issues

### ISSUE THREAD

**Issue by stellarmagnet** [AutarkLabs/open-enterprise#862]
Right now we ask people to estimate time and report actuals, yet this is not exposed in any kind of reporting page

We need to implement a page that exposes these metrics

**Comment by jayalaves** [comment]
Maybe letting the bounty allocator publicly estimate the number of hours is not a good design in itself, since the completion speed is so variable depending on a developer's ability and previous experiences. Or rather, this may be a fine design pattern for predictable tasks, but not all tasks may be predictable in that way.

Alternatively, how about we give the bounty allocator the option to simply insert a bounty reward without any estimate on how long the task will take? Given the reward, in these cases it's up to the developer that wants to tackle the bounty to determine how long it'll take and whether it's worth the involvement for that reward.

**Comment by stellarmagnet** [comment]
> Maybe letting the bounty allocator publicly estimate the number of hours is not a good design in itself, since the completion speed is so variable depending on a developer's ability and previous experiences. Or rather, this may be a fine design pattern for predictable tasks, but not all tasks may be predictable in that way.

Estimating time is basically a way to do math to determine the value. We can call this "points" to make it less time dependent.

> Alternatively, how about we give the bounty allocator the option to simply insert a bounty reward without any estimate on how long the task will take?
Yeah, I think we do need this option as well.

Regardless, we need some value to attach to tickets when funding them. At the end of the day, the developer is looking at a bounty amount, not hours. You'll see there's nowhere in the UI that displays the number of hours besides the initial funding panel.

**Comment by stellarmagnet** [comment]
But in general, I am fine with removing the people who apply for work and submit work to remove the hours part.

But the purpose of this was so project managers can get a better idea of if their own estimates are wrong and that they are under paying people. Sure, it's easy to game though.

**Comment by chadoh** [comment]
There are so many different strategies for dealing with all of this. Every team I've been on does it somewhat differently, even though every single one of them has aspired to be some-sort-of-agile and therefore share some common baseline.

Given that we're trying to build tools for as wide an audience as possible, some of whom may not know the term "points", I wonder how we can design this to allow project/product managers to customize it to their liking. The danger with super customizable interfaces is that they provide no guidance toward proven ways of doing things, though, so it's a hard balance to strike!

I think sticking with "hours" might be fine for now, until we get some user feedback to guide us toward something better.

**Comment by javieralaves** [comment]
Closing this for now since there's no clear direction on whether we want to do any updates on this front.
