### ISSUE TITLE
Issue curation side panel

### ISSUE THREAD

**Issue by stellarmagnet** [AutarkLabs/open-enterprise#932]
**User Story**
As a project manager, after a Dot Vote has concluded for an Issue Curation vote, I would like to see the list of prioritized issues in the projects app. Additionally, I want to be able to create a bounty allocation for this set of issues.

Spec: https://docs.google.com/document/d/1YErknw9EAjo3u-S7VdSXXMtPLfs7LLC8ly4Y7kVtEs0/edit#heading=h.qce16xujhg2c

Design: https://projects.invisionapp.com/d/main#/console/17635937/365601745/preview

**Comment by jayalaves** [comment]
Added some related comments to this on the general Projects review #1023. In regards to this view, my main suggestion was to make the percentage more visible. Here's a suggestion:

<img width="862" alt="Screenshot 2019-07-02 at 12 33 59" src="https://user-images.githubusercontent.com/28843778/60506317-e1112b80-9cc5-11e9-99e4-6444af9464b0.png">

I've reused the progress bar component design from a different view, and in this particular instance I bumped up the ANT tag font size to 14px instead of 13px for a better alignment with the 12px % text.

**Comment by jayalaves** [comment]
This issue has been deprioritized for Cycle A, added it to the pitches page to tackle it in Cycle B.

**Comment by ottodevs** [comment]
Is this still relevant @javieralaves ?

**Comment by javieralaves** [comment]
Not exactly, but the intent to integrate issue curations at some point into Projects stands. I'll cover this in a future issue or epic. Thanks for helping out with the decluttering @ottodevs!
