### ISSUE TITLE
Integrate deep linking in the Projects app

### ISSUE THREAD

**Issue by stellarmagnet** [AutarkLabs/open-enterprise#943]
We should implement deep links for the following pages:
* Project detail page
* Review application panel (per applicant)
* Review work panel (per submission)
* Issues landing page (all projects shown)
  * Note: eventually we should be able to link a specific filter set
* Settings tab 

Reference implementations
* https://github.com/aragon/aragon-apps/pull/1029
* https://github.com/aragon/aragon/pull/846

**Comment by stellarmagnet** [comment]
@ottodevs, what changes need to be made to the Projects contract to be able to display the deep link in the radspec, specifically for the "review submission" part of the flow? E.g. the link is to the work submission of a particular user.

LOC:

https://github.com/AutarkLabs/open-enterprise/blob/6f1612ddd0e2607ebad6a8b139e720c0016501a4/apps/projects/contracts/Projects.sol#L473

**Comment by ottodevs** [comment]
> @ottodevs @topocount , what changes need to be made to the Projects contract to be able to display the deep link in the radspec, specifically for the "review submission" part of the flow? E.g. the link is to the work submission of a particular user. Do we need the radspec IPFS helper to be able to somehow determine the deep link based on the IPFS hash?
> 
> LOC:
> 
> https://github.com/AutarkLabs/open-enterprise/blob/6f1612ddd0e2607ebad6a8b139e720c0016501a4/apps/projects/contracts/Projects.sol#L473

The way you seem to propose, I guess the radspec IPFS helper would be needed to decode the `issueId` from it, because the deep-link is based on the `issueId`.

The alternative approach would be start using the internal github issue numbers, that are already unique, I recently discovered about this approach and it would be really interesting to start using this, since you can decode the internal issue number from the issue id and the other way around... So the change would be start encoding the github issue number into the contract, that way we would not need to use the radspec IPFS helper for this case.

**Comment by javieralaves** [comment]
@ottodevs I notice this issue is connected to a merged PR. Are there any more changes needed before we move this to `Review`?

**Comment by javieralaves** [comment]
Testing this in the continuous deploy DAO on December 20th 2019, everything works as expected!
