### ISSUE TITLE
Projects filters: Display "closed" issues and PRs in the projects app

### ISSUE THREAD

**Issue by stellarmagnet** [AutarkLabs/open-enterprise#944]
Design to do: determine where to fit this in the filters bar

**Comment by jayalaves** [comment]
The pattern from GitHub suggests that we ought to have a tab called _State_ in the tab bar to switch between open and closed issues. No new UI needed but an added space. Following this pattern, which maybe the easiest implementation, we may want to reconsider the wording for the _Status_ tab, since having State and Status could be confusing.

**Comment by stellarmagnet** [comment]
Closing: this should be covered in #1113
