### ISSUE TITLE
Figure out how to get publishing apps to work with our IPFS node. 

### ISSUE THREAD

**Issue by Schwartz10** [AutarkLabs/open-enterprise#982]

**Comment by Schwartz10** [comment]
A successful publish should result in an IPFS hash that represents a directory:

```
 Successfully published address-book.aragonpm.eth v8.0.1: 
 ℹ️ Contract address: 0x0f407B6532BB4092638Ad5CEd2b17BD34d521402
 ℹ️ Content (ipfs): QmcTSkERGGubb38UmcRM9qixsqVbw3qkt8wT6FdvteUpC8
 ℹ️ Transaction hash: 0xb790b8d26f66696137ae95fd4c36f5af12c9ac40300e6d536dea356da641c9bf
ipfs cat /ipfs/QmcTSkERGGubb38UmcRM9qixsqVbw3qkt8wT6FdvteUpC8
Error: this dag node is a directory
ipfs cat /ipfs/QmcTSkERGGubb38UmcRM9qixsqVbw3qkt8wT6FdvteUpC8/artifact.json
```

**Comment by Schwartz10** [comment]
Relates to #981

**Comment by rkzel** [comment]
One potential solution is using haproxy instead of nginx. This needs to be investigated thoroughly, especially given AGP documents which talk about nginx.
Cons:
 - it is not yet known how custom auth modules can be used with haproxy,
Pros:
 - IPFS community recommeded haproxy over nginx,
 - performance, stability, security - haproxy is a specialised tool for precisely the job. nginx is a web server with proxying capabilities,
 - haproxy is confirmed working, nginx behavior is still a mystery,
 - newest version of haproxy has native support for prometheus, our monitoring software of choice.

Conclusion: further investigation and discussion is needed.

**Comment by Schwartz10** [comment]
We can mark this ticket as complete once we deploy a real application on rinkeby and our ipfs node
